sp = float(67.83643)
rj = float(36.67866)
mg = float(29.22988)
es = float(27.16548)
out = float(19.84953)
total = float(sp + rj + mg + es + out)
print(total)
psp = ((sp/total)*100)
prj = ((rj/total)*100)
pmg = ((mg/total)*100)
pes = ((es/total)*100)
pout = ((out/total)*100)

print(f'O percentual de faturamento de SP é: {psp:.2f} %')
print(f'O percentual de faturamento de RJ é: {prj:.2f} %')
print(f'O percentual de faturamento de MG é: {pmg:.2f} %')
print(f'O percentual de faturamento de ES é: {pes:.2f} %')
print(f'O percentual de faturamento de OUT é: {pout:.2f} %')